# Generated by Django 3.1.4 on 2020-12-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranki', '0003_auto_20200512_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='due',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deck',
            name='new',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deck',
            name='total',
            field=models.IntegerField(default=1),
        ),
    ]
