# Generated by Django 3.1.4 on 2020-12-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranki', '0004_auto_20201224_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='due',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deck',
            name='new',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deck',
            name='total',
            field=models.IntegerField(),
        ),
    ]
