# Generated by Django 3.1.4 on 2020-12-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranki', '0005_auto_20201224_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='due',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deck',
            name='new',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deck',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
