# Generated by Django 3.1.4 on 2021-01-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranki', '0006_auto_20201229_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='easiness',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='epetitions',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='interval',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='quality',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(max_length=160, unique=True),
        ),
    ]
